package com.kurui.kums.right._entity;

/**
 * News generated by hbm2java
 */

public class _License

extends org.apache.struts.action.ActionForm implements Cloneable {
	private static final long serialVersionUID = 1L;

	// Fields

	protected long id;
	protected String licenseNo;
	protected String companyNo;
	protected Long staffNum;
	
	protected java.sql.Timestamp issued;
	protected java.sql.Timestamp notafter;
	protected Long licenseType;
	protected String memo;
	protected Long status;
	protected String userNo;

	protected java.sql.Timestamp updateTime;
	
	   

	// The following is extra code specified in the hbm.xml files

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getLicenseNo() {
		return licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	public String getCompanyNo() {
		return companyNo;
	}

	public void setCompanyNo(String companyNo) {
		this.companyNo = companyNo;
	}

	public Long getStaffNum() {
		return staffNum;
	}

	public void setStaffNum(Long staffNum) {
		this.staffNum = staffNum;
	}

	public java.sql.Timestamp getIssued() {
		return issued;
	}

	public void setIssued(java.sql.Timestamp issued) {
		this.issued = issued;
	}

	public java.sql.Timestamp getNotafter() {
		return notafter;
	}

	public void setNotafter(java.sql.Timestamp notafter) {
		this.notafter = notafter;
	}

	public Long getLicenseType() {
		return licenseType;
	}

	public void setLicenseType(Long licenseType) {
		this.licenseType = licenseType;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	public java.sql.Timestamp getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(java.sql.Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code specified in the hbm.xml files

}
