package com.kurui.kums.agent._entity;

// Generated 2012-10-23 19:39:12 by Hibernate Tools 3.2.2.GA

import java.sql.Timestamp;

import com.kurui.kums.agent.Agent;

/**
 * AgentResume generated by hbm2java
 */

public class _AgentResume extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Agent agent;
	protected Long companyId;
	protected String content;
	protected String position;
	protected Timestamp beginTime;
	protected Timestamp endTime;
	protected Long type;
	protected Long status;

	public _AgentResume() {
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Agent getAgent() {

		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	public Long getCompanyId() {

		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getContent() {

		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPosition() {

		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Timestamp getBeginTime() {

		return this.beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}

	public Timestamp getEndTime() {

		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public Long getType() {

		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	// end of extra code

}
