package com.kurui.kums.agent._entity;

// Generated 2012-10-23 19:39:12 by Hibernate Tools 3.2.2.GA

import java.sql.Timestamp;

import com.kurui.kums.agent.Agent;
import com.kurui.kums.transaction.Company;

/**
 * AgentResume generated by hbm2java
 */

public class _AgentResume extends org.apache.struts.action.ActionForm implements
		Cloneable {

	private static final long serialVersionUID = 1L;

	protected long id;
	protected Agent agent;
	protected Company company;
	protected String tag="";
	protected String content="";
	protected Timestamp beginTime;
	protected Timestamp endTime;
	protected Timestamp updateTime;
	protected Long type;
	protected Long status;

	public _AgentResume() {
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Agent getAgent() {

		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	
	
	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getContent() {

		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Timestamp getBeginTime() {

		return this.beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}

	public Timestamp getEndTime() {

		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}
	
	

	public Timestamp getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Long getType() {

		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getStatus() {

		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	// The following is extra code
	public Object clone() {
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	private String thisAction = "";

	public String getThisAction() {
		return thisAction;
	}

	public void setThisAction(String thisAction) {
		this.thisAction = thisAction;
	}

	private int index = 0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}
	
	public String lastAction="";
	public int intPage;
	public int pageCount;
	
	public String getLastAction() {
		return lastAction;
	}

	public void setLastAction(String lastAction) {
		this.lastAction = lastAction;
	}
	
	

	public int getIntPage() {
		return intPage;
	}

	public void setIntPage(int intPage) {
		this.intPage = intPage;
	}

	public int getPageCount() {
		return pageCount;
	}

	public void setPageCount(int pageCount) {
		this.pageCount = pageCount;
	}

	// end of extra code

}
